# -*- coding: utf-8 -*-
"""project on image denoise  by autoencoder

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gyP5Z5Q3m9iD3sVI0T3VbO0yqwZmdNPD
"""

# import libs
import numpy as np
from keras.datasets import mnist
(X_train , _) ,(X_test, _) = mnist.load_data()
#X_train.shape
#(60000, 28, 28)
from matplotlib import pyplot as plt
fig, axes = plt.subplots(2,10, figsize = (16, 4))

count = 0

for i in range(2):
    for j in range(10):
        axes[i,j].imshow(X_train[count], cmap = 'gray')
        count+=1

X_train.shape

X_train = X_train / 255.0
X_test = X_test / 255.0

# prepare source data
noise_factor = 0.1

X_train_noise = X_train + noise_factor * np.random.normal(loc = 0., scale = 1., size = X_train.shape)
X_test_noise = X_test + noise_factor * np.random.normal(loc = 0., scale = 1., size = X_test.shape)
X_train.shape

fig, axes = plt.subplots(2,10, figsize = (16,4))

count = 0
for i in range(2):
    for j in range(10):
        axes[i,j].imshow(X_train_noise[count], cmap = 'gray')
        count+=1

X_train.shape[0]

X_train = X_train.reshape(X_train.shape[0], 28 ,28, 1)
X_test = X_test.reshape(X_test.shape[0], 28,28,1)

X_train_noise = X_train_noise.reshape(X_train_noise.shape[0], 28 ,28, 1)
X_test_noise = X_test_noise.reshape(X_test_noise.shape[0], 28,28,1)

X_train.shape, X_train_noise.shape

from keras.models import Model
from keras.layers import Input, Conv2D, MaxPool2D, Dense, UpSampling2D, BatchNormalization
from keras.callbacks import ModelCheckpoint

import tensorflow as tf
#devices = tf.config.experimental.list_physical_devices("GPU")
#tf.config.experimental.set_memory_growth(devices[0], enable = True)

X_train.shape[1:]

# encoder
encoder_input = Input(shape = X_train.shape[1:])
x = Conv2D(32, (3,3), activation = 'relu', padding = 'same')(encoder_input)
#x = BatchNormalization()(x)
x = MaxPool2D(pool_size = (2,2), padding = 'same')(x)
x = Conv2D(32, (3,3), activation = 'relu', padding = 'same')(x)
#x = BatchNormalization()(x)
encoded = MaxPool2D(pool_size = (2,2), padding = 'same')(x)
# decoder
x = Conv2D(32, (3,3), activation = 'relu', padding = 'same')(encoded)
#x = BatchNormalization()(x)
x = UpSampling2D()(x)
x = Conv2D(32, (3,3), activation = 'relu', padding = 'same')(x)
#x = BatchNormalization()(x)
x = UpSampling2D()(x)
decoded = Conv2D(1, (3,3), activation = 'sigmoid', padding = 'same')(x)
autoencoder = Model(encoder_input, decoded, name = 'Denoising_Model')
autoencoder.summary()

autoencoder.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

autoencoder.fit(X_train_noise, X_train, batch_size = 128, epochs = 5, validation_split = 0.25)

def visualize_data(data, row, column):
    data = data.reshape(data.shape[0], 28,28)
    count = 0
    fig, axes = plt.subplots(row, column, figsize = (16,4))
    for i in range(row):
        for j in range(column):
            axes[i,j].imshow(data[count], cmap = 'gray')
            count+=1

pred = autoencoder.predict(X_test_noise[:20])
pred.shape

visualize_data(pred, 2, 10)